import type { Metadata } from 'next';

import '@/globals.css';
import Link from 'next/link';
import { AuthProvider } from '@/components/providers/AuthProvider';
import Image from 'next/image';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <AuthProvider>
          <header className='text-white shadow-md'>
            <nav className='container mx-auto flex justify-between items-center p-4'>
              <h1 className='text-2xl font-bold'>
                <Link href='/'>
                  <Image src='/moodify.svg' alt='Moodify' width={120} height={32} />
                </Link>
              </h1>
              <div className='space-x-4 text-gray-500'>
                <Link href='/login' className='hover:underline'>
                  Login
                </Link>
                <Link href='/dashboard' className='hover:underline'>
                  Dashboard
                </Link>
                <Link href='/settings' className='hover:underline'>
                  Settings
                </Link>
              </div>
            </nav>
          </header>
          {children}
          <footer className='p-4 mt-4'>
            <p className='text-center text-gray-500'>Moodify © 2024</p>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
