name: Moodify Web Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  lint-type-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn tsc --noEmit

      - name: Check code formatting
        run: yarn prettier --check "**/*.{js,jsx,ts,tsx,json,css,scss,md}"

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

  deploy:
    needs: lint-type-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}
          else
            vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}
          fi

      - name: Build Project Artifacts
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            vercel build --prod --token=${{ env.VERCEL_TOKEN }}
          else
            vercel build --token=${{ env.VERCEL_TOKEN }}
          fi

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}
          else
            echo "DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }})" >> $GITHUB_ENV
          fi

      - name: Comment PR with Deploy URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const deployUrl = process.env.DEPLOY_URL;
            if (deployUrl) {
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `✨ Preview deployment is ready! \n\nDeployed to: ${deployUrl}`
              });
            }
